set(GLAD_INCLUDE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/third_party/glad/include")
set(GLAD_SOURCE      "${CMAKE_CURRENT_SOURCE_DIR}/third_party/glad/src/glad.c")

if(EXISTS "${GLAD_INCLUDE_DIR}/glad/glad.h" AND EXISTS "${GLAD_SOURCE}")
  find_package(OpenGL QUIET)
  if(OpenGL_FOUND)
    if(NOT TARGET GLAD)
      add_library(GLAD INTERFACE)
      target_include_directories(GLAD INTERFACE "${GLAD_INCLUDE_DIR}")
      target_sources(GLAD INTERFACE "${GLAD_SOURCE}")
      add_library(GLAD::GLAD ALIAS GLAD)
    endif()
    set(GLAD_FOUND TRUE)
  else()
    set(GLAD_FOUND FALSE)
  endif()
else()
  set(GLAD_FOUND FALSE)
endif()
